const fs = require("node:fs");
const path = require("node:path");

const artifactPath = path.join(
  __dirname,
  "..",
  "..",
  "artifacts",
  "contracts",
  "SimpleStorage.sol",
  "SimpleStorage.json",
);
const outputDir = path.join(__dirname, "..", "..", "src", "abis");
const outputPath = path.join(outputDir, "SimpleStorage.ts");

function main() {
  if (!fs.existsSync(artifactPath)) {
    console.error(
      `Artifact not found at ${artifactPath}. Did you run \"pnpm compile\"?`,
    );
    process.exit(1);
  }

  const artifact = JSON.parse(fs.readFileSync(artifactPath, "utf8"));
  const abi = artifact.abi;

  fs.mkdirSync(outputDir, { recursive: true });
  const header = "/** Auto-generated by pnpm compile; do not edit manually. */\n";
  const body =
    header +
    "export const SIMPLE_STORAGE_ABI = " +
    JSON.stringify(abi, null, 2) +
    " as const;\n";
  fs.writeFileSync(outputPath, body);

  console.log(`ABI written to ${outputPath}`);
}

main();
